/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SadaqahRouteImport } from './routes/sadaqah'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IslamicRouteImport } from './routes/islamic'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogHowToChooseRouteImport } from './routes/blog.how-to-choose'
import { Route as BlogBestOnlineQuranAcademyRouteImport } from './routes/blog.best-online-quran-academy'
import { Route as BlogBenefitsOfLearningQuranOnlineRouteImport } from './routes/blog.benefits-of-learning-quran-online'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SadaqahRoute = SadaqahRouteImport.update({
  id: '/sadaqah',
  path: '/sadaqah',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IslamicRoute = IslamicRouteImport.update({
  id: '/islamic',
  path: '/islamic',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToChooseRoute = BlogHowToChooseRouteImport.update({
  id: '/how-to-choose',
  path: '/how-to-choose',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBestOnlineQuranAcademyRoute =
  BlogBestOnlineQuranAcademyRouteImport.update({
    id: '/best-online-quran-academy',
    path: '/best-online-quran-academy',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogBenefitsOfLearningQuranOnlineRoute =
  BlogBenefitsOfLearningQuranOnlineRouteImport.update({
    id: '/benefits-of-learning-quran-online',
    path: '/benefits-of-learning-quran-online',
    getParentRoute: () => BlogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faq': typeof FaqRoute
  '/islamic': typeof IslamicRoute
  '/pricing': typeof PricingRoute
  '/sadaqah': typeof SadaqahRoute
  '/teachers': typeof TeachersRoute
  '/blog/benefits-of-learning-quran-online': typeof BlogBenefitsOfLearningQuranOnlineRoute
  '/blog/best-online-quran-academy': typeof BlogBestOnlineQuranAcademyRoute
  '/blog/how-to-choose': typeof BlogHowToChooseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faq': typeof FaqRoute
  '/islamic': typeof IslamicRoute
  '/pricing': typeof PricingRoute
  '/sadaqah': typeof SadaqahRoute
  '/teachers': typeof TeachersRoute
  '/blog/benefits-of-learning-quran-online': typeof BlogBenefitsOfLearningQuranOnlineRoute
  '/blog/best-online-quran-academy': typeof BlogBestOnlineQuranAcademyRoute
  '/blog/how-to-choose': typeof BlogHowToChooseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/faq': typeof FaqRoute
  '/islamic': typeof IslamicRoute
  '/pricing': typeof PricingRoute
  '/sadaqah': typeof SadaqahRoute
  '/teachers': typeof TeachersRoute
  '/blog/benefits-of-learning-quran-online': typeof BlogBenefitsOfLearningQuranOnlineRoute
  '/blog/best-online-quran-academy': typeof BlogBestOnlineQuranAcademyRoute
  '/blog/how-to-choose': typeof BlogHowToChooseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/islamic'
    | '/pricing'
    | '/sadaqah'
    | '/teachers'
    | '/blog/benefits-of-learning-quran-online'
    | '/blog/best-online-quran-academy'
    | '/blog/how-to-choose'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/islamic'
    | '/pricing'
    | '/sadaqah'
    | '/teachers'
    | '/blog/benefits-of-learning-quran-online'
    | '/blog/best-online-quran-academy'
    | '/blog/how-to-choose'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/faq'
    | '/islamic'
    | '/pricing'
    | '/sadaqah'
    | '/teachers'
    | '/blog/benefits-of-learning-quran-online'
    | '/blog/best-online-quran-academy'
    | '/blog/how-to-choose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  FaqRoute: typeof FaqRoute
  IslamicRoute: typeof IslamicRoute
  PricingRoute: typeof PricingRoute
  SadaqahRoute: typeof SadaqahRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sadaqah': {
      id: '/sadaqah'
      path: '/sadaqah'
      fullPath: '/sadaqah'
      preLoaderRoute: typeof SadaqahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islamic': {
      id: '/islamic'
      path: '/islamic'
      fullPath: '/islamic'
      preLoaderRoute: typeof IslamicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-choose': {
      id: '/blog/how-to-choose'
      path: '/how-to-choose'
      fullPath: '/blog/how-to-choose'
      preLoaderRoute: typeof BlogHowToChooseRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/best-online-quran-academy': {
      id: '/blog/best-online-quran-academy'
      path: '/best-online-quran-academy'
      fullPath: '/blog/best-online-quran-academy'
      preLoaderRoute: typeof BlogBestOnlineQuranAcademyRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/benefits-of-learning-quran-online': {
      id: '/blog/benefits-of-learning-quran-online'
      path: '/benefits-of-learning-quran-online'
      fullPath: '/blog/benefits-of-learning-quran-online'
      preLoaderRoute: typeof BlogBenefitsOfLearningQuranOnlineRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogBenefitsOfLearningQuranOnlineRoute: typeof BlogBenefitsOfLearningQuranOnlineRoute
  BlogBestOnlineQuranAcademyRoute: typeof BlogBestOnlineQuranAcademyRoute
  BlogHowToChooseRoute: typeof BlogHowToChooseRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogBenefitsOfLearningQuranOnlineRoute:
    BlogBenefitsOfLearningQuranOnlineRoute,
  BlogBestOnlineQuranAcademyRoute: BlogBestOnlineQuranAcademyRoute,
  BlogHowToChooseRoute: BlogHowToChooseRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  FaqRoute: FaqRoute,
  IslamicRoute: IslamicRoute,
  PricingRoute: PricingRoute,
  SadaqahRoute: SadaqahRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
